### ISSUE TITLE
[Feature Request] Support for Obsidian Mobile

### ISSUE THREAD

**Issue by FelipeRearden** [olrenso/obsidian-home-tab#10]
Hello @olrenso !!!!!

First of all, fantastic idea !!!!!! This is exactly what we need when opening a new tab. The amount of possibilites for this plugin is endless

My first FR is easy to explain: would you mind adding support for **Obsidian Mobile** ?

→ I use Obsidian Mobile on iPad with a mouse and keyboard and I would like to have the same workflow on mobile that I have on Desktop 🙏

🆘 **I tried to enable the plugin on Mobile and checking the Console I found this error:**

```
[error] Plugin failure: home-tab SyntaxError: Invalid regular expression: invalid group specifier name 
```
I was able to find the error using the plugin [Mobile Logging](https://github.com/shabegom/obsidian-mobile-logging)

---

Thanks for reading this!

Have a great day!!!

**Comment by olrenso** [comment]
Thank you for the FR. Currently, the mobile version is disabled since I still need to optimize the Home tab view for smaller screens.

> 🆘 I tried to enable the plugin on Mobile and checking the Console I found this error:
> 
> [error] Plugin failure: home-tab SyntaxError: Invalid regular expression: invalid group specifier name 

It seems related to the [regex expression](https://github.com/olrenso/obsidian-home-tab/blob/918cec18e5d5eda0b3473aca9ed50c1e497896ba/src/utils/isLink.ts#L2) I use to validate links in the settings. I'll take a look into that.

**Comment by FelipeRearden** [comment]
> Thank you for the FR. Currently, the mobile version is disabled since I still need to optimize the Home tab view for smaller screens.

Thank for the feedback and for the reply @olrenso !!!!!

> It seems related to the [regex expression](https://github.com/olrenso/obsidian-home-tab/blob/918cec18e5d5eda0b3473aca9ed50c1e497896ba/src/utils/isLink.ts#L2) I use to validate links in the settings. I'll take a look into that.


Yeah, its the classic issue for plugins on Mobile :) 

I hope its an easy one 🙏

Just to let you know that you can emulate Mobile on Desktop using this command on Console 

![image](https://user-images.githubusercontent.com/85180696/225934541-784068a4-476f-43e7-9808-a414e791c44a.jpeg)


---

Have a great day ☀️

**Comment by olrenso** [comment]
As of [1.1.0](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.0), the plugin should work also on mobile, though I didn't test it extensively.

**Comment by FelipeRearden** [comment]
> As of [1.1.0](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.0), the plugin should work also on mobile, though I didn't test it extensively.

Thank you very much @olrenso !!!! I am gonna start using on Mobile and I let you know if something is strange :)

Thank you very much for this. I wish you a fantastic day ☀️

**Comment by FelipeRearden** [comment]
Hello @

🆘 I found an issue on Mobile :(

🦶 Steps to Reproduce...
1️⃣ Type something in the Search field
2️⃣ Choose a File to open and hit ENTER
3️⃣ In the new active note, you will see that ↑↓ DON'T work. You cant change lines 
4️⃣ If you hit ENTER it will replace the active note with a NEW NOTE that was one of the notes was visible in the Home Tab search field

🐚 **In a nutshell**: after opening a NOTE, looks like that the focus is still in the `Home Tab` instead of the openned note. This way, some keyboard actions will be executed based on the Home Tab instead of the OPENNED Note.

❌ Unfortunately, there is no errors on Console :(

📹 I hope this video helps. I limit the search for 3 files to make easy for us to see the issue 

![video](https://user-images.githubusercontent.com/85180696/226084805-b7250e4d-2da7-4de2-b96b-2dc8acdf4853.MOV)



ℹ️ As you can see, hitting ENTER cycle between the three notes that was suggested in the search field 
- TestLab.TestNote_A
- TestLab.TestNote_D
- TestLab.TestNote_E

**Comment by olrenso** [comment]
Thank you for the detailed bug report. I’ll take a look as soon as possible.

**Comment by olrenso** [comment]
I added a potential fix with [1.1.1](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.1). Let me know if it works.

**Comment by FelipeRearden** [comment]
> I added a potential fix with [1.1.1](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.1). Let me know if it works.

Thank you very much for the quick fix @olrenso !!!!

It's working perfect now. I am gonna stress a little bit more on my main vault and I let you now if I found something strange.

I wish you a fantastic day!!!!

**Comment by olrenso** [comment]
Perfect! I'm closing this FR. If you find any new bugs feel free to open a new issue.

**Comment by FelipeRearden** [comment]
> Perfect! I'm closing this FR. If you find any new bugs feel free to open a new issue.

100% agree @olrenso !!!!

Thanks for all of your attention with this FR :)
