### ISSUE TITLE
[Feature Request] Set as Homepage

### ISSUE THREAD

**Issue by AaronKnowls** [olrenso/obsidian-home-tab#11]
I would love it to open by default whenever Obsidian starts, disregarding the tabs opened on closing. 
Thank so you so much for this brilliant plugin, olrenso.

**Comment by olrenso** [comment]
Do you mean to open a new tab with the plugin view on Obsidian start?

**Comment by olrenso** [comment]
Oh now I see, I'll add it as option.

**Comment by olrenso** [comment]
Closing this FR since it's available in [1.1.1](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.1). If you find any bugs feel free to open a new issue.
