### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ArtemisFowl-san** [olrenso/obsidian-home-tab#12]
Hey, there thanks for the cool plug in. 

The browser-like interaction is a really cool way to interact and be surprised by your vault :)

One thing I really appreciate about Another Quick Switcher is the ability to set the search delay, since otherwise you get very quick updating of the files. Could this also be added to this plug in?

**Comment by olrenso** [comment]
Sure, I'll see what I can do. Did you notice some slowdown when searching?

**Comment by ArtemisFowl-san** [comment]
No, it's not really about slowing down. I just like the delay sometimes when I am looking for something specific and do not want to get shown a lot of unrelated files.

**Comment by olrenso** [comment]
The search delay is now available in the [last release](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.0).
