### ISSUE TITLE
[BUG] Search bar is too short on mobile

### ISSUE THREAD

**Issue by decatetsu** [olrenso/obsidian-home-tab#13]
Search bar on mobile is too short for file names. I think 90-95% width will be enough. Thank you!

![image](https://user-images.githubusercontent.com/56955307/226092182-ba5d4dfc-6d9d-442c-9c38-226ac5a63d3a.png)

**Comment by olrenso** [comment]
Fixed in [1.1.1](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.1) with 5eb218d03f4c79fb49286d810136201ebdcc0bf9
