### ISSUE TITLE
Feature Request: Add recent files to the home-screen

### ISSUE THREAD

**Issue by ernest67** [olrenso/obsidian-home-tab#2]
First of all, thank you for creating this amazing plug-in.
Was wondering whether it is possible to add a **list of recent files** to the homepage, in addition to the starred files?
Thank you!

**Comment by olrenso** [comment]
I added a basic implementation in [1.0.2](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.0.2) that displays the files in the same way as the starred files.
I eventually plan to add a file preview and a contextual menu, [something like firefox](https://i.imgur.com/n3MkfF9.png).

**Comment by ernest67** [comment]
Wonderful, thank you so much!
