### ISSUE TITLE
[Feature Request] Ability to use only a logo, without a title

### ISSUE THREAD

**Issue by rmvdesign** [olrenso/obsidian-home-tab#24]
Love the plugin, but I'd like an option to only use the logo, maybe at a specified size, instead of the text. I've tried to just leave the title text blank, but even at relative size 3, the logo image appears way too small.

**Comment by olrenso** [comment]
With the default logo (or with lucide icons) seems to work fine. It may be a bug with images, I'll fix/improve it in the next release.

**Comment by rmvdesign** [comment]
my bad, i didn't realise the image size was directly connected to text size, even if the text is empty! closed
