### ISSUE TITLE
[FR] Icons for files on the homepage

### ISSUE THREAD

**Issue by dartungar** [olrenso/obsidian-home-tab#3]
Hi there!
Great plugin, I see it becoming really popular.
From top of mind, a few improvements come to mind.

The first is **ability to set icons for starred files showed on the homepage** (similar to Icon Folder plugin - perhaps, an integration?).
Would increase visual appeal of homepage by a lot, at least for some people.

Cheers!

**Comment by olrenso** [comment]
It'll be available in the next release, though only with Lucide icons (for the moment).
Thank you for the FR.
