### ISSUE TITLE
Obsidian Logo Issue

### ISSUE THREAD

**Issue by ParadoxPacer** [olrenso/obsidian-home-tab#49]
is anyone else running into this issue with the home tab plugin where if you set your icon to the default obsidial logo and open a new tab, the icon just appears as a solid color?
![image](https://github.com/user-attachments/assets/1895a771-ddc3-4873-9dfe-f9f7e9e9be44)
Heres the normal logo at startup when the home tab automatically opens.
![image](https://github.com/user-attachments/assets/54dad0c2-f263-4008-8223-1a304ad606e7)
Heres what the logo looks like in every subsequent new tab that i open.
As you can see, it is displayed as a solid color rather than the obsidian logo.

**Comment by zenus260** [comment]
I experience the same. A workaround is to add the Obsidian logo to your vault and reference that within the plugin.

![obsidian-icon](https://github.com/user-attachments/assets/cb8f2239-e069-4afd-982f-b50993636053)
