### ISSUE TITLE
Ability to open multiple files in one search

### ISSUE THREAD

**Issue by Gourav1910** [olrenso/obsidian-home-tab#8]
Hi your plugin is great but there is a small problem. Whenever I search something then suppose I middle mouse click or control click on any search result to open that result in a new tab but when i go back to the previous tab in which the searching tab is open all the search  list disappeared and i have to search things again. Is it possible to click on multiple results to open those notes in the same queried session? (I mean this is what we can do in obsidian's core search)

**Comment by Gourav1910** [comment]
And also if possible I have one more idea. Instead of showing recent files below the search box can you make appearance of list of recent files when we click in the search box (just like it is happen in youtube search box). So in that way we can still see the context of recent files as well such as the folder name and it will make the home tab look much cleaner.

**Comment by olrenso** [comment]
> Is it possible to click on multiple results to open those notes in the same queried session?

Sure, I'll prevent the reset of the search query when opening a file in a new tab.

> Instead of showing recent files below the search box can you make appearance of list of recent files when we click in the search box

I'm working on it.

**Comment by Gourav1910** [comment]
> 

Ok thanks for the reply and for making this amazing plugin. Actually I was thinking about it more like can we embed the search box in any note like our dashboard note so that when we open our dashboard then we can choose to do our query or we can just do other stuff on the dashboard whatever we like. It seems like a dream feature request to me. Is it possible in this plugin?

**Comment by olrenso** [comment]
Actually, based on #4, I was thinking the the exact opposite: a dashboard-like homepage based on widgets where you can eventually embed a note (like your dashboard note).
However, your idea is good too and it may be easier to implement.

Will see.

**Comment by Gourav1910** [comment]
> Actually, based on #4, I was thinking the the exact opposite: a dashboard-like homepage based on widgets where you can eventually embed a note (like your dashboard note). However, your idea is good too and it may be easier to implement.
> 
> Will see.

oh dashboard like homepage would also be a cool idea. Yes if mine one is easier to do then I think you should do both because then people have option to design their dashboard in their own way. But yeah happy to see whatever solution you will come up to.

**Comment by olrenso** [comment]
You should now ([1.1.0](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.0)) be able to open multiple files and embed the search bar in any note.

For the FR regarding the recent file list refer to #5.

**Comment by Gourav1910** [comment]
> You should now ([1.1.0](https://github.com/olrenso/obsidian-home-tab/releases/tag/1.1.0)) be able to open multiple files and embed the search bar in any note.
> 
> For the FR regarding the recent file list refer to #5.

Hi, your plugin embed feature is working as expected in laptop and thank you so much for that. Will it also work in mobile somehow because currently it is just rendering the code and not the search box. 
![image](https://user-images.githubusercontent.com/101202140/226155126-8cc640de-c57c-416d-8d6d-af821b914d45.png)

**Comment by olrenso** [comment]
It works also on mobile. The code block should be `search-bar` and not `search bar`.

**Comment by Gourav1910** [comment]
> It works also on mobile. The code block should be `search-bar` and not `search bar`.

Ok nice thankyou it worked😊🥳
